openapi: 3.0.0
info:
  version: 1.0.0
  title: DOCUMENTATION
  description: ''
  termsOfService: YOUR_TERMS_OF_SERVICE_URL
  contact:
    name: TEAM
    email: contact-email@something.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-generation-date: 02/01/2022 12:55:05 PM
x-strapi-config:
  path: "/documentation"
  showGeneratedFiles: true
  generateDefaultResponse: true
servers:
  - url: http://localhost:1337
    description: Development server
  - url: YOUR_STAGING_SERVER
    description: Staging server
  - url: YOUR_PRODUCTION_SERVER
    description: Production server
externalDocs:
  description: Find out more
  url: https://strapi.io/documentation/developer-docs/latest/getting-started/introduction.html
security:
  - bearerAuth: []
paths:
  "/projects":
    get:
      deprecated: false
      description: ''
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
    post:
      deprecated: false
      description: Create a new record
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProject"
  "/projects/{id}":
    get:
      deprecated: false
      description: ''
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      parameters:
        - name: id
          in: path
          description: ''
          deprecated: false
          required: true
          schema:
            type: string
    put:
      deprecated: false
      description: Update a record
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProject"
      parameters:
        - name: id
          in: path
          description: ''
          deprecated: false
          required: true
          schema:
            type: string
components:
  schemas:
    Project:
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
          maxLength: 255
          minLength: 2
        published_at:
          type: string
          format: date-time
    NewProject:
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 2
        published_at:
          type: string
          format: date-time
        created_by:
          type: string
        updated_by:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Project
